/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Welcome'
    },
    {
      type: 'category',
      label: 'Operating Systems',
      items: [
        {
          type: 'category',
          label: 'Windows',
          items: [
            {
              type: 'category',
              label: 'Powershell',
              link: {
                type: 'doc',
                id: 'OS/windows/powershell/intro',
              },
              items: [
                'OS/windows/powershell/change-font',
                'OS/windows/powershell/oh-my-posh',
              ],
            }]
        },
      ],
    },
    {
      type: 'category',
      label: 'Ruby',
      items: ['Ruby/install-rvm-ruby-linux'],
    },
  ],
};

module.exports = sidebars;
